### ISSUE TITLE
Overflow

### ISSUE THREAD

**Issue by hmachine83** [chenzhaiyu/points2poly#10]
I'm getting this overflow warning/error and it's also happening in helsinki_mini example:
points2poly/utils.py:32: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))

**Comment by chenzhaiyu** [comment]
Hi @hmachine83, the warning is now suppressed with 1f56b252d7f87b4bbb964df7994b1665cf6fb325.

**Comment by hmachine83** [comment]
Thank you!
