### ISSUE TITLE
Performance on indoor planes

### ISSUE THREAD

**Issue by bkhanal-11** [chenzhaiyu/points2poly#11]
Thank you for this amazing work.

I was wondering if this algorithm works well with indoor planes. I have a indoor dataset captured using rgbd camera. I want to simplify the mesh into planar segments. I previously tried polyfit and was only able to get a watertight planar mesh around the structure of the building rather than indoor planar segments like walls and desks. Could you help me with this? Thank you in advance.

**Comment by chenzhaiyu** [comment]
Hi @bkhanal-11, unfortunately both our work and PolyFit assert watertightness on the model to reconstruct. If I understand your case correctly, the un-closed indoor planes are not a good usecase here unless they are expected to form a watertight model.
