### ISSUE TITLE
GPU and dataset

### ISSUE THREAD

**Issue by Hxinyue** [chenzhaiyu/points2poly#12]
Thank you for the great work!
What is the minimum performance of the graphics card used in your experiment? And how to handle my own building point cloud data set for training?

**Comment by chenzhaiyu** [comment]
Hi @Hxinyue, I can't indicate a minimal GPU requirement - we were using RTX 2080 Ti but you should be able to train your model given limited resources with reduced batch size. For training with your own data please see [here](https://github.com/chenzhaiyu/points2poly#custom-dataset).

**Comment by Hxinyue** [comment]
When I tried to run 'python reconstruct.py dataset_name='helsinki_mini' model_name='helsinki_fullview', there was a picture error message.
![1677488413(1)](https://user-images.githubusercontent.com/108390404/221519784-a3608cca-f2ec-4c94-a1a2-798d7957c2aa.jpg)

 I tried 'pip install sage', but the sage package installed seemed to be empty. Is this installed separately in Linux system or another solution?

**Comment by chenzhaiyu** [comment]
Please refer to https://github.com/chenzhaiyu/abspy#install-sagemath for installing Sage. Also note https://github.com/chenzhaiyu/abspy/issues/13.

**Comment by Hxinyue** [comment]
Thank you for your answer! 
Can you provide complete synthetic dataset and real-world point cloud datasets for training and evaluation？

**Comment by Hxinyue** [comment]
[https://github.com/chenzhaiyu/points2poly#reconstruction-from-custom-point-clouds](url)
Is "1. ply" in the folder "00_base_pc" a point or a mesh? There is a point in my own ply file, and then rebuild it according to the prompt. There is no error, and I get a "eval" folder, but there is no "reconstructed" folder

**Comment by chenzhaiyu** [comment]
> Thank you for your answer! Can you provide complete synthetic dataset and real-world point cloud datasets for training and evaluation

We're currently preparing city-wide synthetic data, so stay tuned! The real-world point clouds are courtesy of the first author of https://www.mdpi.com/2072-4292/13/6/1107; please get in touch directly for the data.

> [https://github.com/chenzhaiyu/points2poly#reconstruction-from-custom-point-clouds](url) Is "1. ply" in the folder "00_base_pc" a point or a mesh? There is a point in my own ply file, and then rebuild it according to the prompt. There is no error, and I get a "eval" folder, but there is no "reconstructed" folder

Data in `00_base_pc` should be point clouds, as indicated by the folder name. Likely you're running into the same issue https://github.com/chenzhaiyu/points2poly/issues/7.

**Comment by Hxinyue** [comment]
Excuse me, how can I retrain on my dataset? Thank you for your reply

**Comment by chenzhaiyu** [comment]
Have you prepared your training data?
> Prepare meshes and place them under datasets/{dataset_name} that mimic the structure of the provided data. Refer to this [instruction](https://github.com/ErlerPhilipp/points2surf#make-your-own-datasets) for creating training data through [BlenSor](https://www.blensor.org/) simulation.

Then you can follow the [README](https://github.com/ErlerPhilipp/points2surf) of Points2Surf for training the SDF.

**Comment by Hxinyue** [comment]
Prepare the grid data and put it in the corresponding folder, but there is an error when running the reconstruction
![1678284518(1)](https://user-images.githubusercontent.com/108390404/223734597-3a6f9284-93bf-4e3d-a2d5-46f13f8bf18c.jpg)

**Comment by chenzhaiyu** [comment]
The self-explained “error” indicates no cells are classified as inside, hence no result generated.

Sent from my iPhone

On Mar 8, 2023, at 15:10, Hxinyue ***@***.***> wrote:

﻿

Prepare the grid data and put it in the corresponding folder, but there is an error when running the reconstruction
[1678284518(1)]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F108390404%2F223734597-3a6f9284-93bf-4e3d-a2d5-46f13f8bf18c.jpg&data=05%7C01%7C%7Cf4e6ab8ff7de4e9d7c4308db1fdede6c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638138814287538727%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=26EIPKUUUGvnJaPFqujrjQr0sN2krHvNKIsGnRx3uIE%3D&reserved=0>

**Comment by Hxinyue** [comment]
I don't know whether it is related to my own data set. My building point cloud has many windows; There is another question: Is my "00_base_pc" points (below), or do I need to use Poisson reconstruction to convert it to meshes and put it in this folder?
![points cloud](https://user-images.githubusercontent.com/108390404/223899160-923b75b3-6dac-415a-8bff-07d78d8f0a75.PNG)

**Comment by chenzhaiyu** [comment]
If you convert the point cloud into a .vg/.bvg file and visualize it with Mapple, you can then know whether the dominant planar segments (walls in this case) are extracted. I would suggest finding a good set of RANSAC parameters. Since the point cloud has no bottom, also make sure in config.yaml the append_bottom switch is set to True. You don’t need Poisson.

Sent from my iPhone

On Mar 9, 2023, at 03:23, Hxinyue ***@***.***> wrote:

﻿

I don't know whether it is related to my own data set. My building point cloud has many windows; There is another question: Is my "00_base_pc" points (below), or do I need to use Poisson reconstruction to convert it to meshes and put it in this folder?
[points cloud]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F108390404%2F223899160-923b75b3-6dac-415a-8bff-07d78d8f0a75.PNG&data=05%7C01%7C%7C47955ffdc09b4c68dd1808db20453426%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638139253823273197%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DdQ25rlMu8K2LmeyTyyw1KvS41fl6ecpP2jLWilSqPo%3D&reserved=0>

**Comment by Hxinyue** [comment]
Thanks for your reply！I&nbsp;also make sure in config.yaml the append_bottom switch is set to True，but still get “error: no reachable cells”, do you have any suggestions for the parameters of RANSAC.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenzhaiyu/points2poly"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月9日(星期四) 下午4:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chenzhaiyu/points2poly] GPU and dataset (Issue #12)





 If you convert the point cloud into a .vg/.bvg file and visualize it with Mapple, you can then know whether the dominant planar segments (walls in this case) are extracted. I would suggest finding a good set of RANSAC parameters. Since the point cloud has no bottom, also make sure in config.yaml the append_bottom switch is set to True. You don’t need Poisson. 
 
 Sent from my iPhone 
 
 On Mar 9, 2023, at 03:23, Hxinyue ***@***.***&gt; wrote: 
 
 ﻿ 
 
 I don't know whether it is related to my own data set. My building point cloud has many windows; There is another question: Is my "00_base_pc" points (below), or do I need to use Poisson reconstruction to convert it to meshes and put it in this folder? 
 [points cloud]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F108390404%2F223899160-923b75b3-6dac-415a-8bff-07d78d8f0a75.PNG&amp;data=05%7C01%7C%7C47955ffdc09b4c68dd1808db20453426%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638139253823273197%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=DdQ25rlMu8K2LmeyTyyw1KvS41fl6ecpP2jLWilSqPo%3D&amp;reserved=0&gt;

**Comment by chenzhaiyu** [comment]
One would be to try to reduce the minimal number of support points. You can also play around with the other parameters, while visualizing the corresponding planar segments to make sure it’s okay before ported to the reconstruction.

**Comment by happyfox-xie** [comment]
@Hxinyue  Hello, could you please share your dataset related to buildings? Thank you very much.

**Comment by Hxinyue** [comment]
> @Hxinyue Hello, could you please share your dataset related to buildings? Thank you very much.

Sure. What's your email number？

**Comment by Hxinyue** [comment]
> One would be to try to reduce the minimum number of support points. You can also play around with the other parameters while visualizing the corresponding planar segments to make sure it’s okay before being ported to the reconstruction.

Thank you very much for your reply! I'll try again.

**Comment by happyfox-xie** [comment]
Thanks a lot. My email: ***@***.***&nbsp;


谢斯敬
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月11日(星期六) 上午8:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chenzhaiyu/points2poly] GPU and dataset (Issue #12)





  
@Hxinyue Hello, could you please share your dataset related to buildings? Thank you very much.
  
Sure. What's your email number？

**Comment by Hxinyue** [comment]
Sorry, this seems to be blocked




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenzhaiyu/points2poly"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月11日(星期六) 下午3:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chenzhaiyu/points2poly] GPU and dataset (Issue #12)





 Thanks a lot. My email: ***@***.***&amp;nbsp; 
 
 
 谢斯敬 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2023年3月11日(星期六) 上午8:49 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [chenzhaiyu/points2poly] GPU and dataset (Issue #12) 
 
 
 
 
 
    
 @Hxinyue Hello, could you please share your dataset related to buildings? Thank you very much. 
    
 Sure. What's your email number？

**Comment by Gotta-C** [comment]
same error, I have trained point2surf model in my data, and do different parameters in primitives extraction, and set append_bottom true, reduce coefficient. but still got no unreachable cells. aborting. Can you suggest any way to the right reconstruction?

**Comment by chenzhaiyu** [comment]
> same error, I have trained point2surf model in my data, and do different parameters in primitives extraction, and set append_bottom true, reduce coefficient. but still got no unreachable cells. aborting. Can you suggest any way to the right reconstruction?

Hi, thanks for providing the info. Several factors could be the reason:
* Is it the case that your point clouds are heavily incomplete? In this case the points2surf occupancy indicator may not be an optimal one; 
* Did the points2surf training converge? This can be relevant to the previous factor;
* Have you visualized (at least some of) the primitives to make sure they are ok? For example, if a principal plane is missed out, the reconstruction might fail.

**Comment by Gotta-C** [comment]
> 

the output scene_dense.ply from openmvs after DensifyPointCloud，it can be extracted primitives
![image](https://user-images.githubusercontent.com/20768683/230816170-dacd8ee6-66af-4c22-ac35-d45ec66c49ef.png)
total 1104503 vertex, after primitives extraction
![image](https://user-images.githubusercontent.com/20768683/230816367-c3679e6f-971e-4abe-9302-3967fbb2d2b5.png)
and the output scene_dense_mesh_refine.ply from openmvs after RefineMesh is a mesh which cannot be extracted primitives
![image](https://user-images.githubusercontent.com/20768683/230817175-d04359fa-5465-4838-bb79-8349f9471fc8.png)
my intention is compare a pointclound reconstruction by your work with some plane prior info to the openmvs reconstruction. Is the pointclound accord with standard？and I will check the  points2surf training and visualization

**Comment by chenzhaiyu** [comment]
Hi @Gotta-C, I guess the point cloud per se is okayish as input in terms of the extracted planes. How about the other data in your dataset? It is still possible that the missing points would hinder the points2surf prediction because points2surf to some extent relies on local patches (though it worked on buildings without bottoms).

**Comment by Gotta-C** [comment]
> Hi @Gotta-C, I guess the point cloud per se is okayish as input in terms of the extracted planes. How about the other data in your dataset? It is still possible that the missing points would hinder the points2surf prediction because points2surf to some extent relies on local patches (though it worked on buildings without bottoms).

thanks for the reply，I have tried different scenes，hall，small room，and gets the same problem. Compared to your dataset, the *.vg seems less than 40000 vertex, 15 planes and the points seems very nice. Is it possible that the scene or point clond too large caused?

**Comment by happyfox-dot** [comment]
@Hxinyue Hello, how did you do the modeling of point clouds of buildings without bottoms? Can you share your well-trained model? I can't find the corresponding training data when training my own model :( . Thank you very much.

**Comment by Hxinyue** [comment]
Hello, sorry, I tried to use this method for groundless reconstruction, but always lack of planes could not be generated, I will continue to study it when I have time later, or you have any good ideas to share.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月16日(星期天) 晚上10:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chenzhaiyu/points2poly] GPU and dataset (Issue #12)





 
@Hxinyue Hello, how did you do the modeling of point clouds of buildings without bottoms? Can you share your well-trained model? I can't find the corresponding training data when training my own model :( . Thank you very much.

**Comment by happyfox-dot** [comment]
> 

I'm sorry, I also encountered this problem. Complete the reconstruction in the point cloud data of buildings without bottoms. If I make progress, I would be happy to share with you.

**Comment by chenzhaiyu** [comment]
The Helsinki dataset updated with f194e87.
