### ISSUE TITLE
Shenzhen pointclouds dataset wanted

### ISSUE THREAD

**Issue by happyfox-xie** [chenzhaiyu/points2poly#13]
Hello ,It's  truly a great job! Would you please share the datasets of shenzhen on this paper! Looking forward to your help！

**Comment by chenzhaiyu** [comment]
Hi, I believe this has been addressed in #12.

**Comment by hahahahahahahap** [comment]
@happyfox-dot  Did you get the data set? Would you like to leave an email address to communicate with me?

**Comment by hahahahahahahap** [comment]
@happyfox-dot I tried to contact the author of this data set, but so far they have not responded to me. If you have obtained the data set, I hope we can communicate about it. hh

**Comment by hahahahahahahap** [comment]
@chenzhaiyu Or can you recommend other open source data collections similar to Shenzhen? Thank you very much

**Comment by happyfox-dot** [comment]
> @happyfox-dot I tried to contact the author of this data set, but so far they have not responded to me. If you have obtained the data set, I hope we can communicate about it. hh
Data could be found in this address: [链接](https://pan.baidu.com/s/1PSTQ7KaKH5ARaMh5P0am3w?pwd=mi5t) 
Hope this could help you！

**Comment by hahahahahahahap** [comment]
> > @happyfox-dot I tried to contact the author of this data set, but so far they have not responded to me. If you have obtained the data set, I hope we can communicate about it. hh
> > Data could be found in this address: [链接](https://pan.baidu.com/s/1PSTQ7KaKH5ARaMh5P0am3w?pwd=mi5t)
> > Hope this could help you！
thanks a lot! :-)

**Comment by Silvarebacca** [comment]
> > @happyfox-dot I tried to contact the author of this data set, but so far they have not responded to me. If you have obtained the data set, I hope we can communicate about it. hh
> > Data could be found in this address: [链接](https://pan.baidu.com/s/1PSTQ7KaKH5ARaMh5P0am3w?pwd=mi5t)
> > Hope this could help you！

The link does not seem to work anymore. Could you please upload it again?  Many thanks for your help.

**Comment by Silvarebacca** [comment]
> > > @happyfox-dot I tried to contact the author of this data set, but so far they have not responded to me. If you have obtained the data set, I hope we can communicate about it. hh
> > > Data could be found in this address: [链接](https://pan.baidu.com/s/1PSTQ7KaKH5ARaMh5P0am3w?pwd=mi5t)
> > > Hope this could help you！
> > > thanks a lot! :-)

It seems that the link does not work anymore. Could you please update the link again? Thank you very much for your help.

**Comment by happyfox-dot** [comment]
Okey, the new link is 链接：https://pan.baidu.com/s/1Ehmal8-MGLzjtiiY1UEoFQ?pwd=8t77&nbsp;提取码：8t77 . Hope this would be helpful ,best wishes !





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Silva ***@***.***&gt;; 
发送时间: 2024年8月8日(星期四) 下午4:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chenzhaiyu/points2poly] Shenzhen pointclouds dataset wanted (Issue #13)














    
@happyfox-dot I tried to contact the author of this data set, but so far they have not responded to me. If you have obtained the data set, I hope we can communicate about it. hh
 Data could be found in this address: 链接
 Hope this could help you！
 thanks a lot! :-)
    
It seems that the link does not work anymore. Could you please update the link again? Thank you very much for your help.

**Comment by happyfox-dot** [comment]
> @happyfox-dot I tried to contact the author of this data set, but so far they have not responded to me. If you have obtained the data set, I hope we can communicate about it. hh
Have not worked for this area for a long time. The dataset link is 链接：https://pan.baidu.com/s/1Ehmal8-MGLzjtiiY1UEoFQ?pwd=8t77 . Hope this would be helpful.

**Comment by Silvarebacca** [comment]
> Okey, the new link is 链接：[https://pan.baidu.com/s/1Ehmal8-MGLzjtiiY1UEoFQ?pwd=8t77&nbsp;提取码：8t77](https://pan.baidu.com/s/1Ehmal8-MGLzjtiiY1UEoFQ?pwd=8t77&nbsp;%E6%8F%90%E5%8F%96%E7%A0%81%EF%BC%9A8t77) . Hope this would be helpful ,best wishes !
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Silva ***@***.***&gt;; 发送时间: 2024年8月8日(星期四) 下午4:57 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [chenzhaiyu/points2poly] Shenzhen pointclouds dataset wanted (Issue #13) @happyfox-dot I tried to contact the author of this data set, but so far they have not responded to me. If you have obtained the data set, I hope we can communicate about it. hh Data could be found in this address: 链接 Hope this could help you！ thanks a lot! :-) It seems that the link does not work anymore. Could you please update the link again? Thank you very much for your help. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

Thank you very much and have a good day!
