### ISSUE TITLE
How to better obtain planar primitives.

### ISSUE THREAD

**Issue by happyfox-dot** [chenzhaiyu/points2poly#14]
Hello, this is a great job. However, I have encountered a problem while reconstructing my own data, "Extract planar primitives from point clouds with Mapple." When I need to reconstruct a lot of data on my own, manually obtaining planar primitives will take a lot of time in this step. Is there any other way to complete this task instead of doing it manually? Looking forward to your answer.

**Comment by chenzhaiyu** [comment]
Hello @happyfox-dot, for batch processing of primitive extraction, you could tweak [Easy3D](https://github.com/LiangliangNan/Easy3D). I would suggest checking its [Tutorial_603_Cloud_PlaneExtraction](https://github.com/LiangliangNan/Easy3D/tree/main/tutorials/Tutorial_603_Cloud_PlaneExtraction), where you can easily implement a batch processing CLI.

**Comment by happyfox-dot** [comment]
Thank you very much for your help. I will try to complete it.  👍
