### ISSUE TITLE
ValueError: point coordinates are needed for plane refinement

### ISSUE THREAD

**Issue by Thunderwisking** [chenzhaiyu/points2poly#19]
Hi, thanks a lot for sharing such a brilliant work! 
I want to run the demo code and test its function after preparing the dependencies as the instructions said. When I run: 
```python reconstruct.py dataset_name='helsinki_mini' model_name='helsinki_fullview'```
then I meet:
```
[2023-12-13 21:30:14,735][root][INFO] - processing /home/why/points2poly/datasets/helsinki_mini/06_vertex_group/2.vg
Error executing job with overrides: ['dataset_name=helsinki_mini', 'model_name=helsinki_fullview']
Traceback (most recent call last):
  File "/home/why/points2poly/reconstruct.py", line 51, in reconstruct_full
    cell_complex = create_cell_complex(filepath,
  File "/home/why/points2poly/utils.py", line 69, in create_cell_complex
    cell_complex.refine_planes(theta=theta, epsilon=epsilon)
  File "/home/why/anaconda3/envs/point/lib/python3.10/site-packages/abspy/complex.py", line 127, in refine_planes
    raise ValueError('point coordinates are needed for plane refinement')
ValueError: point coordinates are needed for plane refinement

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

I have no idea about this error. Could you please share your thoughts about  it?

Regards.

**Comment by chenzhaiyu** [comment]
Thanks for reporting this. I think the error comes with the recent release of [`abspy v0.2.4`](https://github.com/chenzhaiyu/abspy/releases) where I introduced OBB into cell complex creation. I assume either simply downgrading `abspy` (e.g., `pip install --upgrade abspy==0.2.3`) or providing the OBB parameter (see this [example](https://github.com/chenzhaiyu/abspy/blob/c49d33aee9178f8981f60bb00da8517c4534a8ca/tests/test_combined.py#L31)) would be a fix. Feel free to shoot a PR.

**Comment by Thunderwisking** [comment]
Thx a lot! Wish you a good day!

**Comment by Thunderwisking** [comment]
Hi, sorry to disturb again. I tried the demo and got very outstanding results. However, when I try to apply the model to my own dataset, the results are not as expected. Given that my dataset may not match the default model, I download whole Helsinki dataset, select some relatively complex buildings, and run the code for several times.  But as these figures show, the model gives a obvious mismatch with the point cloud, which shouldn't make sense.
![e0d2d176f7e7048e61909f2ba508179](https://github.com/chenzhaiyu/points2poly/assets/56376555/6e8f114f-3036-4f2b-8611-46af5eb97b30)
![1704178820419](https://github.com/chenzhaiyu/points2poly/assets/56376555/827fafd5-aa39-4b9b-84b0-78e5cb45833d)
Should I adjust some of parameters to get better results? I tried some but failed. Or is it that I haven't set it up properly？

Regards.

**Comment by chenzhaiyu** [comment]
* You may want to adjust the parameters for plane extraction to make sure no dominate ones are missing.
* The provided _mini_ model is just for a quick demonstration which has not been trained on the whole dataset.
* See also https://github.com/chenzhaiyu/points2poly/issues/6, https://github.com/chenzhaiyu/points2poly/issues/18. Otherwise I would be surprised if the _abspy_ update brings errors.
