### ISSUE TITLE
Running the command `python reconstruct.py dataset_name='helsinki_mini' model_name='helsinki_fullview'` results in the error: `ModuleNotFoundError: No module named 'sage.all'`.

### ISSUE THREAD

**Issue by Zhong0501** [chenzhaiyu/points2poly#26]
The `from sage.all import polytopes, QQ, RR, Polyhedron` statement in `complex.py` is causing an error: `ModuleNotFoundError: No module named 'sage.all'`. My computer is running Windows 10, and I'm using PyCharm as my development platform.
The version of Sage I installed is only 0.0.0. Is this because of the Windows operating system?

**Comment by chenzhaiyu** [comment]
It looks like Sage was not properly installed. Please refer to https://github.com/chenzhaiyu/abspy#faq and https://doc.sagemath.org/html/en/installation/index.html#windows for its installation.

**Comment by Zhong0501** [comment]
@chenzhaiyu 

Thank you for your suggestions. I have set up the environment in WSL, but when I run python reconstruct.py dataset_name='helsinki_mini' model_name='helsinki_fullview', I get an error. The error is shown in the image.
![6d213169daca1c5a941efc4d44b0d25](https://github.com/user-attachments/assets/db7b1134-3095-42ea-9b05-50889dcc947a)

**Comment by chenzhaiyu** [comment]
`aabbs` was introduced since [abspy v0.2.4](https://github.com/chenzhaiyu/abspy/releases/tag/v0.2.4). Which version of `abspy` are you using and how did you install it?

**Comment by fyting** [comment]
> `aabbs` was introduced since [abspy v0.2.4](https://github.com/chenzhaiyu/abspy/releases/tag/v0.2.4). Which version of `abspy` are you using and how did you install it?

v0.2.5
