### ISSUE TITLE
Use My point cloud data

### ISSUE THREAD

**Issue by Zhong0501** [chenzhaiyu/points2poly#27]
"Hello, I have point cloud data in `pcd` format. Can I convert the point cloud to `ply` format and use your reconstruction model to reconstruct the point cloud?"

**Comment by chenzhaiyu** [comment]
Yes, you can convert it first then follow the steps here: [Custom dataset](https://github.com/chenzhaiyu/points2poly#reconstruction-from-custom-point-clouds).

**Comment by Zhong0501** [comment]
Thank you for your reply.
The part about the custom dataset mentions 'Extract planar primitives from point clouds with Maple.' So, I want to ask if there is any relevant documentation on how to use Maple for this purpose?

**Comment by chenzhaiyu** [comment]
Please refer to the documentation of [Easy3D](https://github.com/LiangliangNan/Easy3D).

**Comment by chl916185** [comment]
> Thank you for your reply. The part about the custom dataset mentions 'Extract planar primitives from point clouds with Maple.' So, I want to ask if there is any relevant documentation on how to use Maple for this purpose?

用自己的数据集，可以得到相应的结果吗
@Zhong0501

**Comment by Zhong0501** [comment]
室外点云可以的 @chl916185
