### ISSUE TITLE
about Short tutorial

### ISSUE THREAD

**Issue by amiltonwong** [chenzhaiyu/points2poly#4]
Hi, @chenzhaiyu ,

Where could I find the Short tutorial as mentioned in readme.md ?

Thanks~

**Comment by chenzhaiyu** [comment]
Hi @amiltonwong, at this moment it refers only to the [getting started](https://github.com/chenzhaiyu/points2poly#getting-started) section in README.md, though I might extend it later. Feel free to ask specific questions on the usage, if any.

**Comment by chenzhaiyu** [comment]
Closed for now with https://github.com/chenzhaiyu/points2poly/commit/80a1bc42f69505de28632b32fd92beb33cc85b11. Feel free to reopen it if anything is unclear.
