### ISSUE TITLE
Alternative to using mapple?

### ISSUE THREAD

**Issue by Rifahaziz** [chenzhaiyu/points2poly#8]
Hi, this is amazing work! I had a question for the custom dataset part, is there an alternative python library/tool to use instead of mapple? I am using windows and the mapple executable for windows seem to be outdated. Is there any other alternative to this especially that is python based? Thank you.

**Comment by chenzhaiyu** [comment]
Hi @Rifahaziz, in principle, you can prepare the input point clouds in the generic [VertexGroup](https://abspy.readthedocs.io/en/latest/vertexgroup.html) (just an ASCII file) format using any tools you like - this is not Mapple-specific - though Mapple natively supports it. Yet, I saw @LiangliangNan (kudos👍) recently kindly released [Easy3D-v2.5.1](https://github.com/LiangliangNan/Easy3D/releases/tag/v2.5.1), which comes with an updated Mapple executable for Windows. I would give it a try before looking for alternatives or building a new wheel :)

**Comment by Rifahaziz** [comment]
Hi @chenzhaiyu , mapple works for windows, but the library sage does not. So I could not built it completely on windows.

**Comment by chenzhaiyu** [comment]
Hi @Rifahaziz, this unfortunately cannot be simply solved from my side. I will close this issue for now while keeping https://github.com/chenzhaiyu/abspy/issues/13 open. Please update there if you bump into anything useful!

**Comment by chenzhaiyu** [comment]
@LiangliangNan, we meant [SageMath](https://www.sagemath.org/index.html), on which [abspy](https://github.com/chenzhaiyu/abspy) is built. Unfortunately Sage has discontinued their Windows binaries (see also https://github.com/chenzhaiyu/abspy/issues/13).

**Comment by LiangliangNan** [comment]
Ah, I see. Thanks
